### PR TITLE
.github/workflows: Bump Bazel for testing to 5.0.0

### PR DESCRIPTION
**Pull request by ejona86**
Now you can run locally using the version of your choice.

### CODE REVIEW

**Comment by ejona86** [comment]
@dfawley, friendly ping.

**Review by dfawley — APPROVED** [review]
Surely there's a newer version by now?

**Comment by ejona86** [comment]
Yeah, but for compat reasons I was still planning to upgrade to this older version first (even though I forgot about this PR and was creating a new PR, and then noticed I already had it).

**Comment by ejona86** [comment]
(And although there are newer versions, we tend to support the two most recent versions and Bazel 7 dropped just today.)

**Pull request merged**
