### PR TITLE
Add network_latency_ms field to ALTS's NextHandshakeMessageReq.

### PR DESCRIPTION
**Pull request by matthewstevenson88**
Already internally-reviewed (see cl/589894002 and cl/589974172).

### CODE REVIEW

**Comment by ejona86** [comment]
(FWIW, it tends to be useful to copy the CL number here so we can follow things a bit easier. Especially further in the future and trying to figure out what we did.)

**Comment by ejona86** [comment]
`optional` is not allowed? We should able able to do that, although we may find some places that need upgrades. It looks like the CI here is just using too old a protobuf.

`optional` in proto3 provides presence information, and it looks like you would want that. How much do you care?

**Comment by matthewstevenson88** [comment]
> `optional` is not allowed? We should able able to do that, although we may find some places that need upgrades. It looks like the CI here is just using too old a protobuf.
> 
> `optional` in proto3 provides presence information, and it looks like you would want that. How much do you care?

It's not a big deal in this case, because I only care about the positive values anyway, so "zero" and "not set" are equivalent.

If there's an easy fix to allow `optional` so that the next person doesn't run into this issue (e.g. likely just update the @com_google_protobuf dep to the newest version?), I'm happy to do it in this PR or in a follow-up, whatever you prefer.

**Comment by ejona86** [comment]
> I'm happy to do it in this PR or in a follow-up, whatever you prefer.

Thanks for the offer, but I think I have it. We're going to need to merge https://github.com/grpc/grpc-proto/pull/123 and then bumping past 21.x required a non-obvious line and bumping to 25 required further changes to bazel. I've fought this before in other circumstances.

**Review by ejona86 — APPROVED** [review]

**Comment by matthewstevenson88** [comment]
Thanks Eric!

**Pull request merged**
